title: Funes
description: Event sourcing meta-framework for Rails
url: "https://funes-org.github.io"
baseurl: "/website"

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
